replicaCount: 1
image:
  repository: hazzindu/microserviceone
  tag: 0.0.1
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: NodePort
  externalPort: 8888
  internalPort: 8888
ingress:
  enabled: true
  hosts:
    - serviceone.local
  annotations:
  tls:
resources: {}