replicaCount: 1
image:
  repository: hazzindu/springboot-app
  tag: 2.0.1
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: NodePort
  externalPort: 8080
  internalPort: 8080
ingress:
  enabled: true
  hosts:
    - servicetwo.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
resources: {}